version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: foundry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: foundry
      JWT_SECRET: supersecret
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
